[package]
name = "algos"
version = "0.1.0"
authors = ["Mirolim Mirzakhmedov <mirolim.mirzakhmedov@gmail.com>"]
edition = "2018"

[dependencies]

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "string_benchmark"
harness = false