[package]
name = "algos"
version = "0.1.0"
authors = ["Mirolim Mirzakhmedov <mirolim.mirzakhmedov@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.6.5"

[dev-dependencies]
criterion = "0.2"
walkdir = "2.2.7"
lazy_static = "1.3.0"

[[bench]]
name = "bench_main"
harness = false